### ISSUE TITLE
Add span elements to fragment inside existing elements

### ISSUE THREAD

**Issue by pettarin** [pettarin/icarus#1]
E.g. for sentence- or word- level granularity

**Comment by shermans** [comment]
haha,  I find it myself.

I replace place as '</span> <span>', then .....

**Comment by pettarin** [comment]
Yes, of course you can simulate the functionality with a search-and-replace, using a custom, manually-placed placeholder. What I meant is that ideally one might want to add e.g. ``<span>`` elements for sentences or phrases inside a ``<p>`` element (paragraph), automatically.

Doing so turns out to be a quite challenging problem when you need to consider markup. My current opinion on the matter is that this kind of things should be done on a separate, general-purpose library, and not inside ``icarus`` per se. In fact, I will probably add such a function to my other package ``lachesis``. Once added, ``icarus`` will import the function from ``lachesis``.

Closing this issue for now.
